{% set version = "c0c1647ad62b418f34fe38eb73168d4f2e13ff6f" %}
{% set sha256 = "254dba260b7e8f77edbff9ce271ba6806cca085e084bc23346fcc90015a0c565" %}

{% set build = 0 %}

package:
  name: libactpol
  version: {{ version }}

source:
  url: https://github.com/ACTCollaboration/libactpol/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp # [osx]
    - make
    - automake
    - autoconf
    - m4
    - libtool
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - cfitsio
    - wcslib
    - libactpol_deps
    # Remove until this perl bug is fixed
    # https://github.com/conda-forge/perl-feedstock/issues/56
    - libxcrypt1   # [linux]
    # Not a dependency, force installing a NaMaster-compatible CFITSIO version
    - namaster >=2.4
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("cfitsio") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - {{ pin_compatible("libactpol_deps") }}
    - {{ pin_compatible("wcslib") }}

test:
  commands:
    - ls $PREFIX/lib  # [not win]
    - test -f $PREFIX/lib/libactpol${SHLIB_EXT}  # [not win]

about:
  home: https://github.com/ACTCollaboration/libactpol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library for ACT data I/O.
  description: |
    This is a conda package for libactpol
  dev_url: https://github.com/ACTCollaboration/libactpol

extra:
  recipe-maintainers:
    - tskisner
