
{% set version = "3980cbb579de56a379df000df76e69a1c1ac73ae" %}
{% set sha256 = "e2713145f758631cd6bb24b89a87f2522322a72a29400f8ba51d5144e9afe54d" %}

{% set build = 0 %}

package:
  name: toast
  version: {{ version }}

source:
  url: https://github.com/hpc4cmb/toast/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # patches:
  #   - debug_lapack.patch

build:
  skip: True  # [py<38]
  skip: True  # [win]
  number: {{ build }}
  string: "py{{ py }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - python
    - fftw
    - suitesparse
    - libaatm
    - libflac
  run:
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - python
    - numpy
    - {{ pin_compatible('fftw') }}
    - {{ pin_compatible('suitesparse') }}
    - {{ pin_compatible('libaatm') }}
    - {{ pin_compatible('libflac') }}
    - scipy
    - matplotlib
    - astropy
    - healpy
    - h5py
    - ephem
    - tomlkit
    - traitlets>=5.0
    - psutil
    - pshmem>=0.2.10

test:
  imports:
    - toast

about:
  home: https://github.com/hpc4cmb/toast
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Time Ordered Astrophysics Scalable Tools'
  description: |
    TOAST is a software framework for simulating and processing timestream data
    collected by microwave telescopes.
  dev_url: https://github.com/hpc4cmb/toast

extra:
  recipe-maintainers:
    - tskisner
