{% set version = "0.1.8" %}
{% set sha256 = "0e6d3e32af61524465892c575f92150bbc95aeb6e8349a1369cb013713cd8b7f" %}

{% set build = 0 %}

package:
  name: so3g
  version: {{ version }}

source:
  url: https://github.com/simonsobs/so3g/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup_requires.patch
    - cxx_werror.patch

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - CFLAGS="-Wno-error -O3 -g -fPIC"
    - CXXFLAGS="-Wno-error -O3 -g -fPIC -std=c++14"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make         # [unix]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - python
    - numpy>=1.20
    - scipy
    - boost
    - libflac
  run:
    - openblas * openmp_*
    - libopenblas * openmp_*
    - libblas * *openblas
    - liblapack * *openblas
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('libflac') }}
    - astropy
    - matplotlib
    - scipy
    - ephem
    - pytz
    - pyaml
    - sqlalchemy
    - pysqlite3
    - tqdm

test:
  imports:
    - so3g

about:
  home: https://github.com/simonsobs/so3g
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simons Observatory SPT3G Tools
  description: |
    Glue functions and new classes for SO work in the spt3g paradigm.
  dev_url: https://github.com/simonsobs/so3g

extra:
  recipe-maintainers:
    - tskisner
