{% set version = "0.1.6" %}
{% set sha256 = "50284e8f1c61a0488811791ce05941d5bdd1bd30ab61e2bf6a2f052c1f6cb059" %}

{% set build = 0 %}

package:
  name: so3g
  version: {{ version }}

source:
  url: https://github.com/simonsobs/so3g/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup_requires.patch
    - cxx_werror.patch

build:
  number: {{ build }}
  skip: true  # [win]
  script_env:
    - CFLAGS="-Wno-error -O3 -g -fPIC"
    - CXXFLAGS="-Wno-error -O3 -g -fPIC -std=c++14"
  run_exports:
    - so3g

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - llvm-openmp >=4.0.1  # [osx]
    - libgomp      # [linux]
    - openblas * openmp_*
    - make
  host:
    - llvm-openmp >=4.0.1  # [osx]
    - libgomp      # [linux]
    - openblas * openmp_*
    - python
    - numpy
    - scipy
    - boost
    - libflac
  run:
    - python
    - numpy
    - openblas * openmp_*
    - {{ pin_compatible("liblapack") }}
    - {{ pin_compatible("boost") }}
    - {{ pin_compatible("libflac") }}
    - astropy
    - matplotlib
    - scipy
    - ephem
    - pytz
    - pyaml
    - sqlalchemy
    - pysqlite3
    - tqdm

test:
  imports:
    - so3g

about:
  home: https://github.com/simonsobs/so3g
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simons Observatory SPT3G Tools
  description: |
    Glue functions and new classes for SO work in the spt3g paradigm.
  dev_url: https://github.com/simonsobs/so3g

extra:
  recipe-maintainers:
    - tskisner
