{% set version = "0.1.15" %}
{% set sha256 = "172b203c0f6395c4482d32a8e74f247761f0e380729a8357ef76bc23a581a46c" %}

{% set build = 0 %}

package:
  name: so3g
  version: {{ version }}

source:
  url: https://github.com/simonsobs/so3g/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - setup_requires.patch
    - cxx_werror.patch
    - parallel.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp # [osx]
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - openblas * *openmp*
    - python
    - numpy <2.0
    - scipy
    - boost
    - libboost-devel
    - libboost-python-devel
    - libflac
    - qpoint
    # Although not a dependency, we put numba here to force
    # building with a numba-compatible numpy version
    - numba
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - {{ pin_compatible("libboost-python") }}
    - {{ pin_compatible("libboost") }}
    - {{ pin_compatible("libflac") }}
    - python
    - astropy
    - qpoint
    - matplotlib
    - ephem
    - pytz
    - pyaml
    - sqlalchemy
    - pysqlite3
    - tqdm

test:
  imports:
    - so3g

about:
  home: https://github.com/simonsobs/so3g
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simons Observatory SPT3G Tools
  description: |
    Glue functions and new classes for SO work in the spt3g paradigm.
  dev_url: https://github.com/simonsobs/so3g

extra:
  recipe-maintainers:
    - tskisner
