{% set version = "0.17.3" %}
{% set sha256 = "335742bb22a535add21dd6e63eb9bf35ee98c97efd2795989ca449d1fdc38ad1" %}

{% set build = 0 %}

package:
  name: pixell
  version: {{ version }}

source:
  url: https://github.com/simonsobs/pixell/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  run_exports:
    - pixell

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp >=4.0.1  # [osx]
    - libgomp      # [linux]
  host:
    - llvm-openmp >=4.0.1  # [osx]
    - libgomp      # [linux]
    - automake
    - autoconf
    - m4
    - libtool
    - python
    - cython
    - numpy
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow

test:
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for working with maps in rectangular pixelization.
  description: |
    Library for loading, manipulating and analyzing maps stored 
    in rectangular pixelization.
  dev_url: https://github.com/simonsobs/pixell

extra:
  recipe-maintainers:
    - tskisner
