{% set version = "0.26.1" %}
{% set sha256 = "0aedd7272b2b2ac4aef476d63efb4b6b929d39663f8e3516ceec839896322bcb" %}

{% set build = 0 %}

package:
  name: pixell
  version: {{ version }}

source:
  url: https://github.com/simonsobs/pixell/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - qsort_const.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp # [osx]
    - automake
    - autoconf
    - m4
    - libtool
    - make
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - meson-python
    - cython
    - numpy <2.0
    - scipy
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw
    # Remove until this perl bug is fixed
    # https://github.com/conda-forge/perl-feedstock/issues/56
    - libxcrypt1   # [linux]
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - python
    - astropy
    - healpy
    - matplotlib
    - pyyaml
    - h5py
    - pillow
    - pyfftw

test:
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for working with maps in rectangular pixelization.
  description: |
    Library for loading, manipulating and analyzing maps stored
    in rectangular pixelization.
  dev_url: https://github.com/simonsobs/pixell

extra:
  recipe-maintainers:
    - tskisner
