{% set version = "f0056ac3618b8c4c96130fcb41f7be3d6bd07241" %}
{% set sha256 = "15356bf369bb428a6a8e79b76406d6651b13ca37c18ec8a04c71036c5cc7e35d" %}

{% set build = 0 %}

package:
  name: moby2
  version: {{ version }}

source:
  url: https://github.com/ACTCollaboration/moby2/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # - dep_names.patch
    - np_bool.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    # This is required to ensure consistent use of libgfortran
    # across the stack.
    - {{ compiler('fortran') }}
    - llvm-openmp # [osx]
  host:
    - llvm-openmp # [osx]
    - libgomp # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - fftw
    - gsl
    - libactpol
    - future
    - numpy >=1.26
    - scipy
    # Although not a dependency, we put numba here to force
    # building with a numba-compatible numpy version
    - numba
  run:
    - llvm-openmp # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("scipy") }}
    - {{ pin_compatible("fftw") }}
    - {{ pin_compatible("libopenblas") }}
    - {{ pin_compatible("libblas") }}
    - {{ pin_compatible("gsl") }}
    - {{ pin_compatible("libactpol") }}
    - python
    - future
    - matplotlib
    - astropy
    - ephem
    - pytz

test:
  imports:
    - moby2

about:
  home: https://github.com/ACTCollaboration/moby2
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python tools for ACT
  description: |
    This is a conda package for moby2
  dev_url: https://github.com/ACTCollaboration/moby2

extra:
  recipe-maintainers:
    - tskisner
