name:  Test Build

on: workflow_dispatch

jobs:
  test:
    name: Tests on ${{ matrix.arch }} with Conda Python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    env:
      CI: "1"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
            arch: Linux-x86_64
          - os: ubuntu-latest
            python: "3.11"
            arch: Linux-x86_64
          - os: macos-latest
            python: "3.10"
            arch: MacOSX-x86_64
          - os: macos-latest
            python: "3.11"
            arch: MacOSX-x86_64
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda Base
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python }}
          auto-update-conda: true
          # conda-solver: libmamba
          # auto-activate-base: true
          activate-environment: soconda_CI

      - name: Check Conda Config
        run: |
          conda activate base
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Install
        run: |
          ./soconda.sh -e soconda -v CI

      - name: Run Tests
        run: |
          conda activate "soconda_CI"
          export OMP_NUM_THREADS=2
          export MPI_DISABLE=1
          export CI=1
          python3 -c 'import toast.tests; toast.tests.run()'
          git clone --depth=1 --single-branch --branch=master https://github.com/simonsobs/sotodlib.git
          pushd sotodlib
          python3 setup.py test
          popd
          unset MPI_DISABLE
          unset OMP_NUM_THREADS
